spring:
  datasource:
    url: jdbc:postgresql://s1.iarch.tech:5432/postgres
    username: postgres.your-tenant-id
    password: EU.tech24
    driver-class-name: org.postgresql.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.demo.entity
